on: [push]

env:
  RUST_LOG: info
  RUST_BACKTRACE: 1

jobs:
  check:
    name: Run clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: clippy
      - run: cd sdp8xx/ && cargo clippy && cd -

  build:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy
      - name: Run tests
        run: cd sdp8xx/ && cargo test --verbose && cd -

  miri-test:
    name: Test with miri
    runs-on: ubuntu-latest
    env:
      MIRIFLAGS: Mon
    steps:
      - uses: actions/checkout@v2
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly
          components: miri
      - run: cd sdp8xx/ && MIRIFLAGS=-Zmiri-disable-isolation cargo miri test --verbose --no-default-features && cd -
      - run: cd sdp8xx/ && MIRIFLAGS=-Zmiri-disable-isolation cargo miri test --verbose --all-features && cd -

  rustfmt:
    name: Verify code formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hecrj/setup-rust-action@v1
        with:
          components: rustfmt
      - run: cd sdp8xx/ && cargo fmt --all -- --check && cd -

